name: coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    name: "coverage"
    steps:
    - uses: actions/checkout@v2
    - name: install lcov
      run: brew install lcov
    - name: build
      run: .ci/build_coverage.sh
