name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { cc: "gcc-7", cxx: "g++-7" }
        - { cc: "gcc-8", cxx: "g++-8" }
        - { cc: "gcc-9", cxx: "g++-9" }
        - { cc: "gcc-10", cxx: "g++-10" }
        - { cc: "clang-8", cxx: "clang++-8" }
        - { cc: "clang-9", cxx: "clang++-9" }
        - { cc: "clang-10", cxx: "clang++-10" }
    name: "${{matrix.compiler.cxx}}"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: .ci/build_linux.sh
      env:
        CC: ${{matrix.compiler.cc}}
        CXX: ${{matrix.compiler.cxx}}
